### ISSUE TITLE
Board always trying to open ble port even if serial is specified 

### ISSUE THREAD

**Issue by Nilon123456789** [Nilon123456789/firmetix#3]
The board is always trying to set the device mode to BLE even if there is no BLE device name assigned.

See traceback

```
WARNING: ble name given, but connection type is serial. Changing connection type to BLE
Firmetix:  Version 7.0.0

Copyright (c) 2023 Nils Lahaye All Rights Reserved.

[INFO] SimpleBLE: D:\a\SimpleBLE\SimpleBLE\simpleble\src\backends\windows\Utils.cpp:33 in initialize_winrt: CoGetApartmentType: cotype=-1, qualifier=0, result=800401F0
[INFO] SimpleBLE: D:\a\SimpleBLE\SimpleBLE\simpleble\src\backends\windows\Utils.cpp:41 in initialize_winrt: RoInitialize: result=0
Found 1 Bluetooth adapters
        Using adapter 0: TEKAMLAPTOP - Front
Looking for a compatible ble device...
Traceback (most recent call last):
  File "main.py", line 2, in <module>
    firmetix.Firmetix(arduino_instance_id=board_id, com_port=COM_port, arduino_wait=2, connection_type=0)
  File "venv\lib\site-packages\firmetix\firmetix.py", line 376, in init__
    self._find_arduino_ble()
  File "venv\lib\site-packages\firmetix\firmetix.py", line 556, in _find_arduino_ble
    raise RuntimeError(f'No BLE devices found with name {self.ble_name}')
RuntimeError: No BLE devices found with name Firmetix4ESP_BLE_1
```

**Comment by Nilon123456789** [comment]
Fixed in commit [c432553](https://github.com/Nilon123456789/firmetix/commit/c4325538534e6dc6660a5e7a1ace19ec169f1eaa)
